import React from 'react';
import type { AIInsights, ContractRiskLevel } from '../../types';
import { SparklesIcon, CheckCircleIcon, XCircleIcon, InfoCircleIcon } from '../icons/IconComponents';

interface AIInsightsPanelProps {
  insights: AIInsights;
  onExtractClauses: () => void;
  isExtracting: boolean;
}

const riskConfig: Record<ContractRiskLevel, { color: string; bgColor: string; icon: React.FC<{className?:string}> }> = {
  Low: { color: 'text-green-700', bgColor: 'bg-green-100', icon: CheckCircleIcon },
  Medium: { color: 'text-yellow-700', bgColor: 'bg-yellow-100', icon: InfoCircleIcon },
  High: { color: 'text-red-700', bgColor: 'bg-red-100', icon: XCircleIcon },
};

const RiskBadge: React.FC<{ level: ContractRiskLevel }> = ({ level }) => {
  const { color, bgColor, icon: Icon } = riskConfig[level];
  return (
    <div className={`flex items-center p-3 rounded-lg ${bgColor}`}>
      <Icon className={`w-6 h-6 mr-3 ${color}`} />
      <div>
        <p className="text-sm font-semibold text-gray-600">Risk Level</p>
        <p className={`text-lg font-bold ${color}`}>{level}</p>
      </div>
    </div>
  );
};

const AIInsightsPanel: React.FC<AIInsightsPanelProps> = ({ insights, onExtractClauses, isExtracting }) => {
  return (
    <div className="bg-white rounded-lg shadow p-6 space-y-6">
      <RiskBadge level={insights.riskLevel} />

      <div>
        <h4 className="text-sm font-semibold text-gray-800 flex items-center">
            <SparklesIcon className="w-5 h-5 mr-2 text-primary-500" />
            AI Summary
        </h4>
        <ul className="mt-3 list-disc list-inside space-y-2 text-sm text-gray-600">
            {insights.summary.map((point, index) => (
                <li key={index}>{point}</li>
            ))}
        </ul>
        <p className="text-xs text-gray-400 mt-2 text-right">
            Summary generated by Gemini
        </p>
      </div>
      
      <div className="border-t border-gray-200 pt-4">
        <h4 className="text-sm font-semibold text-gray-800">Key Clauses Extracted</h4>
        
        {insights.extractedClauses.length > 0 ? (
           <div className="mt-3 space-y-3">
              {insights.extractedClauses.map((clause, index) => (
                  <div key={index} className="p-3 bg-gray-50 rounded-md transition-all hover:bg-gray-100">
                      <p className="font-semibold text-sm text-gray-700">{clause.title}</p>
                      <p className="text-xs text-gray-600 mt-1 line-clamp-2 hover:line-clamp-none">{clause.content}</p>
                  </div>
              ))}
          </div>
        ) : (
          <div className="mt-3 text-center">
            {isExtracting ? (
              <div className="flex items-center justify-center text-gray-500 text-sm p-3">
                <svg className="animate-spin -ml-1 mr-3 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <span>Extracting with Gemini...</span>
              </div>
            ) : (
              <>
                <p className="text-sm text-gray-500">No clauses have been extracted yet.</p>
                <button 
                  onClick={onExtractClauses}
                  className="mt-2 inline-flex items-center text-sm font-semibold px-4 py-2 rounded-lg text-white bg-primary-600 hover:bg-primary-700 shadow transition-colors"
                >
                  <SparklesIcon className="w-4 h-4 mr-2"/>
                  Extract with AI
                </button>
              </>
            )}
          </div>
        )}
      </div>

    </div>
  );
};

export default AIInsightsPanel;